#export PATH="$HOME/bin:/usr/local/bin:$PATH"
#export PATH=$PATH:"/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"
#export PATH="/anaconda3/bin:$PATH:/Library/TeX/texbin"
#export PYTHONPATH="/usr/local/python3.6/site-packages"
#export PATH="$HOME/bin:/anaconda3/bin:/usr/local/bin:/usr/local/sbin:$PATH:/Library/TeX/texbin"
#export PATH="/usr/local/Cellar/emacs-plus/26.2/Emacs.app/Contents/MacOS:$PATH"
typeset -U path
path=(/usr/local/opt/coreutils/libexec/gnubin /usr/local/Cellar/emacs-plus/26.2/Emacs.app/Contents/MacOS /bin /usr/local/bin $HOME/bin  /usr/local/sbin /Library/TeX/texbin $path )
. /anaconda3/etc/profile.d/conda.sh
#export PATH="$HOME/bin:/anaconda3/bin:/usr/local/bin:/usr/local/sbin:$PATH:/Library/TeX/texbin"
#export PATH="/usr/local/Cellar/emacs-plus/26.2/Emacs.app/Contents/MacOS:$PATH"
#
#PATH="$PATH"
